export const clerkAppearance = {
  variables: {
    colorBackground: "#0a0c11",
    colorText: "#e2e4ea",
    colorTextSecondary: "#9aa0aa",
    colorPrimary: "#7c6fff",
    colorInputBackground: "#10131a",
    colorInputText: "#e2e4ea",
    colorNeutral: "#1a1d28",
    borderRadius: "8px",
  },
  elements: {
    cardBox: "bg-[#0a0c11] border border-white/10 shadow-2xl",
    card: "bg-[#0a0c11] text-[#e2e4ea]",
    headerTitle: "text-[#f4f5f8]",
    headerSubtitle: "text-[#9aa0aa]",
    socialButtonsBlockButton: "border-white/10 bg-[#10131a] text-[#e2e4ea] hover:bg-white/10",
    socialButtonsBlockButtonText: "text-[#e2e4ea]",
    formFieldLabel: "text-[#c9cdd6]",
    formFieldInput: "border-white/10 bg-[#10131a] text-[#e2e4ea] placeholder:text-[#6f7683]",
    footerActionText: "text-[#9aa0aa]",
    footerActionLink: "text-[#b7b0ff] hover:text-white",
    modalContent: "bg-[#0a0c11] text-[#e2e4ea]",
    modalCloseButton: "text-[#e2e4ea] hover:bg-white/10",
    navbar: "bg-[#0a0c11] border-white/10",
    navbarButton: "text-[#e2e4ea] hover:bg-white/10",
    navbarButtonIcon: "text-[#9aa0aa]",
    profileSectionTitle: "text-[#f4f5f8]",
    profileSectionSubtitle: "text-[#9aa0aa]",
    formButtonPrimary: "bg-[#7c6fff] text-white hover:bg-[#6b60e8]",
    userButtonPopoverCard: "bg-[#0a0c11] border border-white/10 text-[#e2e4ea]",
    userButtonPopoverMain: "bg-[#0a0c11] text-[#e2e4ea]",
    userButtonPopoverActionButton: "text-[#e2e4ea] hover:bg-white/10",
    userButtonPopoverActionButtonText: "text-[#e2e4ea]",
    userButtonPopoverActionButtonIcon: "text-[#9aa0aa]",
    userButtonPopoverUserPreview: "text-[#e2e4ea]",
    userButtonPopoverUserPreviewMainIdentifier: "text-[#f4f5f8]",
    userButtonPopoverUserPreviewSecondaryIdentifier: "text-[#9aa0aa]",
    userButtonPopoverFooter: "hidden",
  },
};
